"""add creator_username to db

Revision ID: b6ebe69c6cad
Revises: 01de80fcec61
Create Date: 2026-07-20 12:22:56.995918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ebe69c6cad'
down_revision: Union[str, None] = '01de80fcec61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('creator_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'creator_username')
    # ### end Alembic commands ###
