"""add calculations table

Revision ID: f7db3f772800
Revises: 9f93e36bf7bf
Create Date: 2026-04-20 12:40:54.835916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7db3f772800'
down_revision: Union[str, None] = '9f93e36bf7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('calcultaion')
    op.alter_column('calculations', 'result',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_calculations_id'), 'calculations', ['id'], unique=False)
    op.create_foreign_key(None, 'calculations', 'users', ['username'], ['username'])
    op.drop_column('calculations', 'created_at')
    op.add_column('products', sa.Column('description', sa.String(), nullable=False))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.alter_column('products', 'price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'description')
    op.add_column('calculations', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'calculations', type_='foreignkey')
    op.drop_index(op.f('ix_calculations_id'), table_name='calculations')
    op.alter_column('calculations', 'result',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_table('calcultaion',

    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name=op.f('refresh_tokens_username_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    # ### end Alembic commands ###
